name: Scala CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job para hacer el build de mi proyecto
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
  # Job para hacer el artefacto    
  artifact:
    needs: build
    runs-on: ubuntu-latest 
    steps: 
    - name: upload artifact
      uses: actions/upload-artifact@v2 
      with: 
        name: scala_artifact 
        path: /*
      
  
